/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interface_potus;

import javax.swing.JOptionPane;

/**
 *
 * @author GABRIEL
 */
public class consultaforn extends javax.swing.JFrame {

    /**
     * Creates new form consultaforn
     */
    public consultaforn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_cnpjforn = new javax.swing.JTextField();
        txt_nomeforn = new javax.swing.JTextField();
        txt_descforn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cb_codforn = new javax.swing.JComboBox();
        btn_save = new javax.swing.JButton();
        btn_alt = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btn_cons = new javax.swing.JButton();
        btn_voltar = new javax.swing.JButton();
        menu_barra = new javax.swing.JMenuBar();
        mn_login = new javax.swing.JMenu();
        mn_login_func = new javax.swing.JMenuItem();
        mn_login_gerente = new javax.swing.JMenuItem();
        mn_func = new javax.swing.JMenu();
        mn_func_cad = new javax.swing.JMenuItem();
        mn_func_cons = new javax.swing.JMenuItem();
        mn_prod = new javax.swing.JMenu();
        mn_prod_cad = new javax.swing.JMenuItem();
        mn_prod_cons = new javax.swing.JMenuItem();
        mn_forn = new javax.swing.JMenu();
        mn_forn_cad = new javax.swing.JMenuItem();
        mn_forn_cons = new javax.swing.JMenuItem();
        mn_forn_gerap = new javax.swing.JMenuItem();
        mn_forn_consp = new javax.swing.JMenuItem();
        mn_nota = new javax.swing.JMenu();
        mn_nota_gera = new javax.swing.JMenuItem();
        mn_nota_hist = new javax.swing.JMenuItem();
        mn_estoque = new javax.swing.JMenu();
        mn_estoque_cons = new javax.swing.JMenuItem();
        mn_finan = new javax.swing.JMenu();
        mn_finan_lista = new javax.swing.JMenuItem();
        mn_finan_relat = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Consulta Fornecedor");

        jLabel5.setText("CNPJ:");

        jLabel4.setText("Descrição:");

        txt_cnpjforn.setEditable(false);

        txt_nomeforn.setEditable(false);

        txt_descforn.setEditable(false);

        jLabel3.setText("Nome:");

        jLabel2.setText("Código:");

        cb_codforn.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", " " }));

        btn_save.setText("Salvar");
        btn_save.setEnabled(false);

        btn_alt.setText("Alterar");

        jLabel7.setText("Ao Clicar em 'Alterar' os campos se tornam editáveis e o 'Salvar' se Habilita.");

        btn_cons.setText("Consultar");
        btn_cons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consActionPerformed(evt);
            }
        });

        btn_voltar.setText("Voltar");
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });

        mn_login.setText("Login");

        mn_login_func.setText("Login Funcionário");
        mn_login_func.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_login_funcActionPerformed(evt);
            }
        });
        mn_login.add(mn_login_func);

        mn_login_gerente.setText("Login Gerente");
        mn_login.add(mn_login_gerente);

        menu_barra.add(mn_login);

        mn_func.setText("Funcionário");

        mn_func_cad.setText("Cadastro ");
        mn_func_cad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_func_cadActionPerformed(evt);
            }
        });
        mn_func.add(mn_func_cad);

        mn_func_cons.setText("Consulta/Altera");
        mn_func_cons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_func_consActionPerformed(evt);
            }
        });
        mn_func.add(mn_func_cons);

        menu_barra.add(mn_func);

        mn_prod.setText("Produto");

        mn_prod_cad.setText("Cadastro");
        mn_prod_cad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_prod_cadActionPerformed(evt);
            }
        });
        mn_prod.add(mn_prod_cad);

        mn_prod_cons.setText("Consulta/Altera ");
        mn_prod_cons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_prod_consActionPerformed(evt);
            }
        });
        mn_prod.add(mn_prod_cons);

        menu_barra.add(mn_prod);

        mn_forn.setText("Fornecedor");

        mn_forn_cad.setText("Cadastro");
        mn_forn_cad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_forn_cadActionPerformed(evt);
            }
        });
        mn_forn.add(mn_forn_cad);

        mn_forn_cons.setText("Consulta/Alterar");
        mn_forn_cons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_forn_consActionPerformed(evt);
            }
        });
        mn_forn.add(mn_forn_cons);

        mn_forn_gerap.setText("Gerar Pedido");
        mn_forn_gerap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_forn_gerapActionPerformed(evt);
            }
        });
        mn_forn.add(mn_forn_gerap);

        mn_forn_consp.setText("Alterar/Consultar Pedido");
        mn_forn_consp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_forn_conspActionPerformed(evt);
            }
        });
        mn_forn.add(mn_forn_consp);

        menu_barra.add(mn_forn);

        mn_nota.setText("Notas");

        mn_nota_gera.setText("Gerar Nota");
        mn_nota.add(mn_nota_gera);

        mn_nota_hist.setText("Histórico");
        mn_nota.add(mn_nota_hist);

        menu_barra.add(mn_nota);

        mn_estoque.setText("Estoque");

        mn_estoque_cons.setText("Consultar/Alterar");
        mn_estoque_cons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_estoque_consActionPerformed(evt);
            }
        });
        mn_estoque.add(mn_estoque_cons);

        menu_barra.add(mn_estoque);

        mn_finan.setText("Financeiro");

        mn_finan_lista.setText("Listar Contas");
        mn_finan.add(mn_finan_lista);

        mn_finan_relat.setText("Relatório");
        mn_finan_relat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_finan_relatActionPerformed(evt);
            }
        });
        mn_finan.add(mn_finan_relat);

        menu_barra.add(mn_finan);

        setJMenuBar(menu_barra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btn_cons)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_alt, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addComponent(btn_save)
                                .addGap(25, 25, 25)
                                .addComponent(btn_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cb_codforn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_descforn, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txt_cnpjforn, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_nomeforn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cb_codforn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_nomeforn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_cnpjforn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_descforn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cons)
                    .addComponent(btn_alt)
                    .addComponent(btn_save)
                    .addComponent(btn_voltar))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mn_login_funcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_login_funcActionPerformed

        new Login().setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_mn_login_funcActionPerformed

    private void mn_func_cadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_func_cadActionPerformed
        new Cadastro().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_mn_func_cadActionPerformed

    private void mn_func_consActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_func_consActionPerformed
        new consultaf().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_mn_func_consActionPerformed

    private void mn_prod_cadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_prod_cadActionPerformed
        new cadastrop().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_mn_prod_cadActionPerformed

    private void mn_prod_consActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_prod_consActionPerformed

        new consultap().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_mn_prod_consActionPerformed

    private void mn_forn_cadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_forn_cadActionPerformed
        new cadastroforn().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_mn_forn_cadActionPerformed

    private void mn_forn_consActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_forn_consActionPerformed
        new consultaforn().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_mn_forn_consActionPerformed

    private void mn_forn_gerapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_forn_gerapActionPerformed
        new gerapedido().setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_mn_forn_gerapActionPerformed

    private void mn_forn_conspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_forn_conspActionPerformed
        new Consultapedido().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_mn_forn_conspActionPerformed

    private void mn_estoque_consActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_estoque_consActionPerformed
        new Consultae().setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_mn_estoque_consActionPerformed

    private void mn_finan_relatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_finan_relatActionPerformed
        new relatorio().setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_mn_finan_relatActionPerformed

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
        consultaforn.this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_voltarActionPerformed

    private void btn_consActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consActionPerformed
        // TODO add your handling code here:
        String nome, cod, cnpj, desc;
        
        nome = txt_nomeforn.getText();
        cnpj = txt_cnpjforn.getText();
                
        if(nome.isEmpty()|| cnpj.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Por favor, preencha todos os campos!!");
        }
    }//GEN-LAST:event_btn_consActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(consultaforn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(consultaforn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(consultaforn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(consultaforn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new consultaforn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_alt;
    private javax.swing.JButton btn_cons;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JComboBox cb_codforn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar menu_barra;
    private javax.swing.JMenu mn_estoque;
    private javax.swing.JMenuItem mn_estoque_cons;
    private javax.swing.JMenu mn_finan;
    private javax.swing.JMenuItem mn_finan_lista;
    private javax.swing.JMenuItem mn_finan_relat;
    private javax.swing.JMenu mn_forn;
    private javax.swing.JMenuItem mn_forn_cad;
    private javax.swing.JMenuItem mn_forn_cons;
    private javax.swing.JMenuItem mn_forn_consp;
    private javax.swing.JMenuItem mn_forn_gerap;
    private javax.swing.JMenu mn_func;
    private javax.swing.JMenuItem mn_func_cad;
    private javax.swing.JMenuItem mn_func_cons;
    private javax.swing.JMenu mn_login;
    private javax.swing.JMenuItem mn_login_func;
    private javax.swing.JMenuItem mn_login_gerente;
    private javax.swing.JMenu mn_nota;
    private javax.swing.JMenuItem mn_nota_gera;
    private javax.swing.JMenuItem mn_nota_hist;
    private javax.swing.JMenu mn_prod;
    private javax.swing.JMenuItem mn_prod_cad;
    private javax.swing.JMenuItem mn_prod_cons;
    private javax.swing.JTextField txt_cnpjforn;
    private javax.swing.JTextField txt_descforn;
    private javax.swing.JTextField txt_nomeforn;
    // End of variables declaration//GEN-END:variables
}
